# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da571fce69ab15a9465c7b323a3ee9e1105294faaaa7681c57e5f973698d38f9956201b487628f95442f252cad4457d7827d63ddbea57f2c83fc7910f774c935

test:
  secret_key_base: c1157fca977766c32f7a6e08886e36903a1458fc970d4f29f7f93adea721bea356368a896aaf63c7527d1cfcf805801cefe9cbbfd8ff42b29ad1dbdba984a0b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
